#CSV file with 
changefilename: 'chamber-change.csv'

# Identifier field with name of each chamber (should be the same in both CSV results and GeoJSON boundaries file)
chamberIdentifier: 'state'

# Column name from CSV file with the formatted name of each chamber
chamberName: 'name_formal'


# Name of first party (left)
partyLeftName: 'Democrats'
# Name of second party (right)
partyRightName: 'Republicans'
# Name of other party 
partyOtherName: 'Other'


# GeoJSON file with district boundaries
geojson: 'districts.geojson'


#Change report geometries
localpolygeojson: 'districts.geojson'
localcentgeojson: 'geometry/lo-cent.geojson'
statepolygeojson: 'geometry/us.geojson'


# Output directory for saving infographics
outputDirectory: 'change-reports'
